### ISSUE TITLE
The new build fails when we load it in GCP

### ISSUE THREAD

**Issue by pundaripothini** [nash-md/twilio-contact-center#30]
Lots of errors around missing workflow etc,. I had to rollback to the version from April 29th for it to work. Any ideas? Nothing works, I couldn't run the /setup I get into syntax errors etc,. very bizarre.

**Comment by nash-md** [comment]
I tested with the latest repository version and Heroku and it was working finde. Can you post the error message here? How did  you upgrade?

**Comment by pundaripothini** [comment]
Hi MD,

I uploaded it to GCP cloud and I consistently get this error:

error: configuration could not be loaded

But when I upload the April 29th build following exact same steps it's a
success.

**Comment by pundaripothini** [comment]
Hi,

I work for a company that delivers a lot of twilio based solutions and we
have a constant need for twilio skills expertise. We don't have any
in-house development and heavily rely on external vendors/partners. But my
current partners often struggle with twilio based solutions and I'm trying
to see if it's feasible to use external resources and independent hobby
coders to help with our journey. Let me know if you are interested. This
can be helping with coding or be available on a consultative basis,
whichever you feel comfortable with.

Kind regards
Pundari Pothini

**Comment by nash-md** [comment]
Can you check if the error still occurs after you reload the page? The reason is, **app.js** will try to create the entity if it does not exist, nevertheless there is no async/await currently and the first load will fail, this is something I need to fix in the future. If this does not work, please delete the Firestore storage for this app, it should then re-create it. Again you would need to start the app twice.
